tasks:
    path: /tareas
    controller: App\Controller\TaskController::index
    
task_detail:
    path: /tarea/{id}
    controller: App\Controller\TaskController::detail

task_creation:
    path: /crear-tarea
    controller: App\Controller\TaskController::creation
    
my_tasks:
    path: /mis-tareas
    controller: App\Controller\TaskController::myTasks
    
task_edit:
    path: /editar-tarea/{id}
    controller: App\Controller\TaskController::edit
    
task_delete:
    path: /borrar-tarea/{id}
    controller: App\Controller\TaskController::delete

user_list:
    path: /users
    controller: App\Controller\UserController::listUsers

user_edit:
    path: /users/{id}/edit
    controller: App\Controller\UserController::edit

user_delete:
    path: /users/{id}
    controller: App\Controller\UserController::delete

register:
    path: /registro
    controller: App\Controller\UserController::register
    
login:
    path: /
    controller: App\Controller\UserController::login
    
logout:
    path: /logout
